chore: add check for manifest.json presence in main_workflow.yml

diff --git a/.github/workflows/main_workflow.yml b/.github/workflows/main_workflow.yml
--- a/.github/workflows/main_workflow.yml
+++ b/.github/workflows/main_workflow.yml
@@ -42,6 +42,13 @@ jobs:
           API_URL: ${{ secrets.API_URL }}
         continue-on-error: false
 
+      - name: Check manifest.json presence
+        run: |
+          if [ ! -f ./dist/manifest.json ]; then
+            echo "manifest.json not found in ./dist";
+            exit 1;
+          fi
+
       - name: Run tests
         run: npm run test:coverage --if-present
         continue-on-error: false
